### ISSUE TITLE
The text-transform: capitalize; statement could interfere with IP such as the names/trademarks of other companies

### ISSUE THREAD

**Issue by jlprevatt** [RedHatInsights/insights-chrome#900]
I noticed this issue when doing some comparisons of current subscription watch left navigation menus:

- https://cloud.redhat.com/subscriptions/rhel-sw/all

- https://ci.cloud.redhat.com/beta/subscriptions/rhel-sw/all

Specifically, I noticed the change from "IBM Z systems" (as listed on the IBM Z product pages) to "IBM Z Systems." I mentioned it to my UX team, who pointed me to the code change.

For the `insights-chrome/src/js/App/Sidenav/Navigation.scss` file, the following code could interfere with the intellectual property of other companies. 

`.ins-c-sidebar .pf-c-nav .pf-c-nav__link {
    text-transform: capitalize; // All nav links should be in title case, remove CSC as a dependent for this
}`

RE the usage of other company/product name trademarks (and non-trademarked names of products) in the nav menu, has the potential legal impact of this change been reviewed?

**Comment by ryelo** [comment]
The reason we're using the `text-transform` is due to the standard of using Title Case in the navigation for the applications. We're trying to eliminate as many dependencies as possible. We want the Title Case to be the standard and then any other case to be the exception (instead of the other way around due to the amount of apps using one or the other).

However, I understand the concern and it's something that we can fix a couple of ways. Ideally, we can add a flag to cloud-services-config (the config repo to draw the nav) in order to ignore the casing. For the time being, however, because of the imports, applications themselves are able to update the CSS of anything on the page (including chrome), so if there is a certain navigation element that needs the `text-transform` property to change, that can be changed by the app. In this example, you could just do:

```
.pf-c-nav__link[ouia-nav-item="ibmpower"] {
    text-transform: none !important;
}
```

the `ouia-nav-item` is the same ID used here (https://github.com/RedHatInsights/cloud-services-config/blob/9a6a88ca1198cc8e55526567b145b4217151ffe5/main.yml#L444)

**Comment by ryelo** [comment]
PR Opened: https://github.com/RedHatInsights/insights-chrome/pull/901

**Comment by ryelo** [comment]
PR has been merged. You can add `ignoreCase: true` for anything with the `title` field in order to ignore the style and force the capitalization you provide.

example:

```
rhel-sw:
  title: Red Hat Enterprise Linux
  frontend:
    sub_apps:
      - id: all
        title: All
        default: true
      - id: arm
        title: ARM
      - id: ibmpower
        title: IBM Power
      - id: ibmz
        title: IBM Z systems
        ignoreCase: true
      - id: x86
        title: x86
```
